### ISSUE TITLE
PyPi Package

### ISSUE THREAD

**Issue by MattIPv4** [dhocker/uDMX-pyusb#5]
Could the base pyudmx package be published to PyPi please?
Would be great to be able to have a requirement for it in other packages and not having a local copy of the package.

**Comment by dhocker** [comment]
I'll see about doing this next week. I'm trying to come with two packages by using versions/tags. One package is Python 2 and 3 compatible. The other package will require Python 3.5 or better.

I appreciate your pull request. However, the introduction of typehints posed a bit of a dilemma. typehints was introduced in Python 3.5, so adopting it means backward compatibility with Python 2 is lost. My solution is to create a Python 2/3 compatible release at udmx-pyusb tag 1.1.0. After that, I'll change the version/tag to 2.0.0 and merge your pull request. It'll take me some time to test out your pull request on my Raspberry Pi.

**Comment by MattIPv4** [comment]
Sounds good. I use PyCharm whilst adding the typehints and it threw no errors, which implies it thinks all the typehints are correct based on the returns / uses of args.

**Comment by dhocker** [comment]
I have created a udmx-pyusb package on PyPI. There are two versions of the package: 1.1.1 and 2.0.0. The 1.1.1 package is compatible with Python 2 and 3 while the 2.0.0 package requires Python 3.5+. Both packages require pyusb 1.0.2 or better (which is installed as a dependency).

To install version 1.1.1 use: 
```
pip install 'udmx-pyusb==1.1.1'
```
To install the latest version 1.x.x use:
```
pip install 'udmx-pyusb<2.0.0'
```
To install version 2.0.0 or the latest version:
```
pip install udmx-pyusb
```

You can check out the releases at [PyPI](https://pypi.org/manage/project/udmx-pyusb/releases/)
